#!/usr/bin/env bash
# isntall and configures HAProxy

sudo apt-get update
sudo apt-get install haproxy -y

config_details="
frontend haproxy-1
    bind *:80
    mode http
    default_backend server_group1
backend server_group1
    balance roundrobin
    server 56638-web-01 54.160.115.113:80 check
    server 56638-web-02 100.25.221.226:80 check
"
sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "$config_details" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
